# Data Preprocessing and Analysis

In [12]:
import pandas as pd

In [13]:
dfmovies = pd.read_csv("movie_cleaned_data.csv")
dfmovies.head()

,Unnamed: 0,MovieName,StoryLine
0,113,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...
1,131,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ..."
2,133,All for One,Sara a young Morisco unmasks the three muskete...
3,155,Beyond existence,"Following a psychedelic experience, two young ..."
4,163,Mr Zoo Keeper,A zookeeper and his relationship with the anim...

In [14]:
dfmovies.isnull().sum()

Unnamed: 0       0
MovieName        0
StoryLine     3703
dtype: int64

In [15]:
dfmovies['StoryLine'] = dfmovies['StoryLine'].fillna(dfmovies['MovieName'])
dfmovies.isnull().sum()

Unnamed: 0    0
MovieName     0
StoryLine     0
dtype: int64

## Text Cleaning (NLP):

In [26]:
import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [27]:
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to C:\Users\Lathiga
[nltk_data]     Magasri\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to C:\Users\Lathiga
[nltk_data]     Magasri\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Lathiga
[nltk_data]     Magasri\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [29]:
print(dfmovies['StoryLine'].head())  # Check the first few rows
print(dfmovies['StoryLine'].isnull().sum())  # Check for null values
print(dfmovies['StoryLine'].apply(type).value_counts())  # Check data types

0    Epic quest pits fearless outlaw Diana and knig...
1    Simon, a 16-year-old suffocated by his strict ...
2    Sara a young Morisco unmasks the three muskete...
3    Following a psychedelic experience, two young ...
4    A zookeeper and his relationship with the anim...
Name: StoryLine, dtype: object
0
StoryLine
<class 'str'>    12395
Name: count, dtype: int64

In [30]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [32]:
def NLP_preprocess(text):
    if not isinstance(text, str) or text.strip() == "":  # Handle non-string or empty values
        return ""
    try:
        text = text.lower()
        text = re.sub(r'[^a-z\s]', '', text)  # Remove non-alphabetic characters
        tokens = word_tokenize(text)  # Tokenize the text
        tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]  # Lemmatize and remove stopwords
        return ' '.join(tokens)  # Join tokens back into a single string
    except Exception as e:
        print(f"Error processing text: {text}")
        print(f"Error: {e}")
        return ""

In [33]:
dfmovies['Cleaned_Storyline'] = dfmovies['StoryLine'].apply(NLP_preprocess)

In [36]:
dfmovies.head()  # Display the first 10 rows of the DataFrame

,Unnamed: 0,MovieName,StoryLine,Cleaned_Storyline
0,113,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...,epic quest pit fearless outlaw diana knight ty...
1,131,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ...",simon yearold suffocated strict mormon upbring...
2,133,All for One,Sara a young Morisco unmasks the three muskete...,sara young morisco unmasks three musketeer pro...
3,155,Beyond existence,"Following a psychedelic experience, two young ...",following psychedelic experience two young wom...
4,163,Mr Zoo Keeper,A zookeeper and his relationship with the anim...,zookeeper relationship animal bird remain zoo

In [ ]:
dfmovies['Cleaned_Storyline'].isnull().sum()

np.int64(0)

In [ ]:

dfmovies['Cleaned_Storyline'].apply(type).value_counts()

Cleaned_Storyline
<class 'str'>    12395
Name: count, dtype: int64

In [ ]:

dfmovies['Cleaned_Storyline'].head(10)

0    epic quest pit fearless outlaw diana knight ty...
1    simon yearold suffocated strict mormon upbring...
2    sara young morisco unmasks three musketeer pro...
3    following psychedelic experience two young wom...
4        zookeeper relationship animal bird remain zoo
5    comedy three couple unknowingly book house fam...
6    featurelength film based story pobeda berlin l...
7    group space ranger must protect universe extin...
8    gilgamesh king uruk abuse power prompting god ...
9    movieend world dubbed hollywood movie end worl...
Name: Cleaned_Storyline, dtype: object

In [43]:
dfmovies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12395 entries, 0 to 12394
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         12395 non-null  int64
 1   MovieName          12395 non-null  object
 2   StoryLine          12395 non-null  object
 3   Cleaned_Storyline  12395 non-null  object
dtypes: int64(1), object(3)
memory usage: 387.5+ KB

## Text Representation:

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(max_features=1000)

In [46]:
count_matrix = count_vectorizer.fit_transform(dfmovies['Cleaned_Storyline'])

In [48]:
dfmoviescount = pd.DataFrame(count_matrix.toarray(), columns=count_vectorizer.get_feature_names_out())

In [49]:
dfmovies['Count_Vector'] = list(dfmoviescount.values)

In [51]:
dfmovies.head()

,Unnamed: 0,MovieName,StoryLine,Cleaned_Storyline,Count_Vector
0,113,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...,epic quest pit fearless outlaw diana knight ty...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,131,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ...",simon yearold suffocated strict mormon upbring...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,133,All for One,Sara a young Morisco unmasks the three muskete...,sara young morisco unmasks three musketeer pro...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,155,Beyond existence,"Following a psychedelic experience, two young ...",following psychedelic experience two young wom...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,163,Mr Zoo Keeper,A zookeeper and his relationship with the anim...,zookeeper relationship animal bird remain zoo,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [52]:
dfmovies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12395 entries, 0 to 12394
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         12395 non-null  int64
 1   MovieName          12395 non-null  object
 2   StoryLine          12395 non-null  object
 3   Cleaned_Storyline  12395 non-null  object
 4   Count_Vector       12395 non-null  object
dtypes: int64(1), object(4)
memory usage: 484.3+ KB

## Cosine Similarity:

In [54]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
count_matrix = np.array(dfmovies['Count_Vector'].to_list())
count_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(12395, 1000))

In [56]:
cosine_sim_matrix = cosine_similarity(count_matrix)
cosine_sim_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(12395, 12395))

In [58]:
def get_ranked_movies(index, cosine_sim_matrix, movies_df, top_n=5):
    sim_scores = list(enumerate(cosine_sim_matrix[index]))
    sorted_sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    top_movies = sorted_sim_scores[1:top_n+1]
    ranked_movies = [dfmovies.iloc[i]['MovieName'] for i, score in top_movies]
    return ranked_movies

In [59]:
dfmovies['Ranked_Movies'] = [
    get_ranked_movies(i, cosine_sim_matrix, dfmovies) for i in range(len(dfmovies))
]
dfmovies[['MovieName', 'Ranked_Movies']].head(10)

               MovieName                                      Ranked_Movies
0    The Last Redemption  [Njerëz dhe Fate 2, Fate, Between Silence and ...
1    This Too Shall Pass  [On the Border, Border Senjôkisha × Islam Koku...
2            All for One  [How the West Was One, Being Mummy G.O., The B...
3       Beyond existence  [M.O.E.T.: Money Over Everything, Frida Khalo ...
4          Mr Zoo Keeper  [A Few Mornings, an Evening, A House in Fragme...
5         Odio el verano  [Ciao, Haye Bibiye Kithe Fas Gaye, Welcome Wed...
6   Rocky Road to Berlin  [Billy Preston: That's the Way God Planned It,...
7           Space Ranger  [Release, Space Shuttle, Lesbian Vampires from...
8  The Epic of Gilgamesh  [Mana Atua - The Power of God, El Laberinto de...
9           Tapori Nayak  [My World 2, Psycho World Tournament, Winding ...

In [60]:
dfmovies.head()

,Unnamed: 0,MovieName,StoryLine,Cleaned_Storyline,Count_Vector,Ranked_Movies
0,113,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...,epic quest pit fearless outlaw diana knight ty...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Njerëz dhe Fate 2, Fate, Between Silence and ..."
1,131,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ...",simon yearold suffocated strict mormon upbring...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[On the Border, Border Senjôkisha × Islam Koku..."
2,133,All for One,Sara a young Morisco unmasks the three muskete...,sara young morisco unmasks three musketeer pro...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[How the West Was One, Being Mummy G.O., The B..."
3,155,Beyond existence,"Following a psychedelic experience, two young ...",following psychedelic experience two young wom...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[M.O.E.T.: Money Over Everything, Frida Khalo ..."
4,163,Mr Zoo Keeper,A zookeeper and his relationship with the anim...,zookeeper relationship animal bird remain zoo,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[A Few Mornings, an Evening, A House in Fragme..."

In [61]:
dfmovies = dfmovies.drop(columns  = ['Unnamed: 0'])
dfmovies.head()

,MovieName,StoryLine,Cleaned_Storyline,Count_Vector,Ranked_Movies
0,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...,epic quest pit fearless outlaw diana knight ty...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Njerëz dhe Fate 2, Fate, Between Silence and ..."
1,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ...",simon yearold suffocated strict mormon upbring...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[On the Border, Border Senjôkisha × Islam Koku..."
2,All for One,Sara a young Morisco unmasks the three muskete...,sara young morisco unmasks three musketeer pro...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[How the West Was One, Being Mummy G.O., The B..."
3,Beyond existence,"Following a psychedelic experience, two young ...",following psychedelic experience two young wom...,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[M.O.E.T.: Money Over Everything, Frida Khalo ..."
4,Mr Zoo Keeper,A zookeeper and his relationship with the anim...,zookeeper relationship animal bird remain zoo,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[A Few Mornings, an Evening, A House in Fragme..."

In [62]:
dfmovies.to_csv("movie_vector_data.csv")

In [63]:
dfmovies = dfmovies.drop(columns  = ['Count_Vector', 'Ranked_Movies'])
dfmovies.head()

,MovieName,StoryLine,Cleaned_Storyline
0,The Last Redemption,Epic quest pits fearless outlaw Diana and knig...,epic quest pit fearless outlaw diana knight ty...
1,This Too Shall Pass,"Simon, a 16-year-old suffocated by his strict ...",simon yearold suffocated strict mormon upbring...
2,All for One,Sara a young Morisco unmasks the three muskete...,sara young morisco unmasks three musketeer pro...
3,Beyond existence,"Following a psychedelic experience, two young ...",following psychedelic experience two young wom...
4,Mr Zoo Keeper,A zookeeper and his relationship with the anim...,zookeeper relationship animal bird remain zoo

In [65]:
dfmovies.to_csv("movie_cleaned_data.csv", index=False)